import { IProduct } from "./productStore";

export const products: IProduct[] = [
  {
    id: 1,
    name: "Guitarra Modelo 1",
    category: "Guitarras",
    price: 2500.0,
    image: "",
  },
  {
    id: 2,
    name: "Guitarra Modelo 2",
    category: "Guitarras",
    price: 3500.0,
    image: "",
  },
  {
    id: 3,
    name: "Guitarra Modelo 3",
    category: "Guitarras",
    price: 6000.0,
    image: "",
  },
  {
    id: 4,
    name: "Guitarra Modelo 4",
    category: "Guitarras",
    price: 4200.0,
    image: "",
  },
  {
    id: 5,
    name: "Guitarra Modelo 5",
    category: "Guitarras",
    price: 18000.0,
    image: "",
  },
  {
    id: 6,
    name: "Guitarra Modelo 6",
    category: "Guitarras",
    price: 8000.0,
    image: "",
  },
  {
    id: 7,
    name: "Guitarra Modelo 7",
    category: "Guitarras",
    price: 22000.0,
    image: "",
  },
  {
    id: 8,
    name: "Guitarra Modelo 8",
    category: "Guitarras",
    price: 28000.0,
    image: "",
  },
  {
    id: 9,
    name: "Guitarra Modelo 9",
    category: "Guitarras",
    price: 3000.0,
    image: "",
  },
  {
    id: 10,
    name: "Guitarra Modelo 10",
    category: "Guitarras",
    price: 15000.0,
    image: "",
  },
  {
    id: 11,
    name: "Contrabaixo Modelo 1",
    category: "Contrabaixos",
    price: 8000.0,
    image: "",
  },
  {
    id: 12,
    name: "Contrabaixo Modelo 2",
    category: "Contrabaixos",
    price: 10000.0,
    image: "",
  },
  {
    id: 13,
    name: "Contrabaixo Modelo 3",
    category: "Contrabaixos",
    price: 12000.0,
    image: "",
  },
  {
    id: 14,
    name: "Contrabaixo Modelo 4",
    category: "Contrabaixos",
    price: 14000.0,
    image: "",
  },
  {
    id: 15,
    name: "Contrabaixo Modelo 5",
    category: "Contrabaixos",
    price: 16000.0,
    image: "",
  },
  {
    id: 16,
    name: "Contrabaixo Modelo 6",
    category: "Contrabaixos",
    price: 18000.0,
    image: "",
  },
  {
    id: 17,
    name: "Contrabaixo Modelo 7",
    category: "Contrabaixos",
    price: 20000.0,
    image: "",
  },
  {
    id: 18,
    name: "Contrabaixo Modelo 8",
    category: "Contrabaixos",
    price: 22000.0,
    image: "",
  },
  {
    id: 19,
    name: "Contrabaixo Modelo 9",
    category: "Contrabaixos",
    price: 24000.0,
    image: "",
  },
  {
    id: 20,
    name: "Contrabaixo Modelo 10",
    category: "Contrabaixos",
    price: 26000.0,
    image: "",
  },
];
